/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/uS99KVr3aDl
 */
import Link from "next/link";
import { Input } from "@/app/ui/input";
import { Button } from "@/app/ui/button";
import { CardContent, Card } from "@/app/ui/card";
import Navbar from "../ui/navbar";
import Footer from "../ui/footer";

export const revalidate = 3600;

export default function Events() {
	return (
		<div className="flex flex-col min-h-[100dvh] ">
			<Navbar />
			<main className="flex-1">
				<section className="flex items-center justify-center w-full min-h-[60vh] py-6 md:py-12 lg:py-24 xl:py-32">
					<div className=" px-4 md:px-6 flex flex-col items-center justify-center space-y-2 text-center">
						<div className="space-y-2">
							<h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl text-white">
								Upcoming Events
							</h1>
							<p className="mx-auto max-w-[600px] text-black md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed ">
								Explore our exciting lineup of events happening this Pearl.
							</p>
						</div>
						<div className="mx-auto max-w-sm !mt-7">
							<Link
								className="px-4 py-2 bg-white rounded-md hover:bg-gray-100 "
								href={"#events"}
							>
								Purchase Tickets
							</Link>
						</div>
					</div>
				</section>
				<section className="w-full py-12 md:py-24 lg:py-32 ">
					<div className=" px-4 md:px-6 grid items-center gap-6 text-center lg:grid-cols-[1fr_600px] lg:gap-12">
						<div className="space-y-2">
							<h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl/none">
								Featured Events
							</h2>
							<p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed ">
								Check out our highlighted events and mark your calendars.
							</p>
						</div>
						<div className="mx-auto w-full max-w-2xl space-y-4">
							<div className="grid gap-4">
								<Card>
									<CardContent className="flex items-center space-x-4">
										<img
											alt="Event"
											className="rounded-lg overflow-hidden aspect-square object-cover object-center"
											height="100"
											src="/placeholder.svg"
											width="100"
										/>
										<div className="space-y-1">
											<h3 className="text-xl font-bold">
												Summer Music Festival
											</h3>
											<p className="text-sm text-gray-500 ">
												August 20-22, 2023
											</p>
										</div>
									</CardContent>
								</Card>
								<Card>
									<CardContent className="flex items-center space-x-4">
										<img
											alt="Event"
											className="rounded-lg overflow-hidden aspect-square object-cover object-center"
											height="100"
											src="/placeholder.svg"
											width="100"
										/>
										<div className="space-y-1">
											<h3 className="text-xl font-bold">Food Truck Rally</h3>
											<p className="text-sm text-gray-500 ">
												September 5, 2023
											</p>
										</div>
									</CardContent>
								</Card>
								<Card>
									<CardContent className="flex items-center space-x-4">
										<img
											alt="Event"
											className="rounded-lg overflow-hidden aspect-square object-cover object-center"
											height="100"
											src="/placeholder.svg"
											width="100"
										/>
										<div className="space-y-1">
											<h3 className="text-xl font-bold">Art Exhibition</h3>
											<p className="text-sm text-gray-500 ">
												October 12-15, 2023
											</p>
										</div>
									</CardContent>
								</Card>
							</div>
						</div>
					</div>
				</section>
				<section
					id="events"
					className="w-full py-12 md:py-24 lg:py-32 bg-gray-100"
				>
					<div className="px-4 md:px-6 flex flex-col items-center justify-center space-y-2 text-center">
						<div className="space-y-2">
							<h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl/none">
								All Events
							</h2>
							<p className="mx-auto max-w-[600px] text-black md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed ">
								Register for our upcoming events and get your tickets now.
							</p>
						</div>
					</div>
				</section>
			</main>
			<Footer />
		</div>
	);
}
